/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/_settings'
import { Route as FilesRouteImport } from './routes/files'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SharedRouteImport } from './routes/shared'
import { Route as SharedWithMeRouteImport } from './routes/shared-with-me'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as TasksIdRouteImport } from './routes/tasks_.$id'
import { Route as SettingsSettingsIndexRouteImport } from './routes/_settings.settings.index'
import { Route as SettingsSettingsApiKeysRouteImport } from './routes/_settings.settings.api-keys'
import { Route as SettingsSettingsAppearanceRouteImport } from './routes/_settings.settings.appearance'
import { Route as SettingsSettingsBotsRouteImport } from './routes/_settings.settings.bots'
import { Route as SettingsSettingsChannelsRouteImport } from './routes/_settings.settings.channels'
import { Route as SettingsSettingsPeriodicJobsRouteImport } from './routes/_settings.settings.periodic-jobs'
import { Route as SettingsSettingsSessionsRouteImport } from './routes/_settings.settings.sessions'
import { Route as SettingsSettingsUploadsRouteImport } from './routes/_settings.settings.uploads'
import { Route as SettingsSettingsUsersRouteImport } from './routes/_settings.settings.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/_settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedRoute = SharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedWithMeRoute = SharedWithMeRouteImport.update({
  id: '/shared-with-me',
  path: '/shared-with-me',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/tasks_/$id',
  path: '/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSettingsIndexRoute = SettingsSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSettingsApiKeysRoute = SettingsSettingsApiKeysRouteImport.update({
  id: '/settings/api-keys',
  path: '/settings/api-keys',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSettingsAppearanceRoute =
  SettingsSettingsAppearanceRouteImport.update({
    id: '/settings/appearance',
    path: '/settings/appearance',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsSettingsBotsRoute = SettingsSettingsBotsRouteImport.update({
  id: '/settings/bots',
  path: '/settings/bots',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSettingsChannelsRoute =
  SettingsSettingsChannelsRouteImport.update({
    id: '/settings/channels',
    path: '/settings/channels',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsSettingsPeriodicJobsRoute =
  SettingsSettingsPeriodicJobsRouteImport.update({
    id: '/settings/periodic-jobs',
    path: '/settings/periodic-jobs',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsSettingsSessionsRoute =
  SettingsSettingsSessionsRouteImport.update({
    id: '/settings/sessions',
    path: '/settings/sessions',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsSettingsUploadsRoute = SettingsSettingsUploadsRouteImport.update({
  id: '/settings/uploads',
  path: '/settings/uploads',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSettingsUsersRoute = SettingsSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/files': typeof FilesRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/shared': typeof SharedRoute
  '/shared-with-me': typeof SharedWithMeRoute
  '/storage': typeof StorageRoute
  '/tasks': typeof TasksRoute
  '/trash': typeof TrashRoute
  '/share/$token': typeof ShareTokenRoute
  '/tasks/$id': typeof TasksIdRoute
  '/settings/api-keys': typeof SettingsSettingsApiKeysRoute
  '/settings/appearance': typeof SettingsSettingsAppearanceRoute
  '/settings/bots': typeof SettingsSettingsBotsRoute
  '/settings/channels': typeof SettingsSettingsChannelsRoute
  '/settings/periodic-jobs': typeof SettingsSettingsPeriodicJobsRoute
  '/settings/sessions': typeof SettingsSettingsSessionsRoute
  '/settings/uploads': typeof SettingsSettingsUploadsRoute
  '/settings/users': typeof SettingsSettingsUsersRoute
  '/settings/': typeof SettingsSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/files': typeof FilesRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/shared': typeof SharedRoute
  '/shared-with-me': typeof SharedWithMeRoute
  '/storage': typeof StorageRoute
  '/tasks': typeof TasksRoute
  '/trash': typeof TrashRoute
  '/share/$token': typeof ShareTokenRoute
  '/tasks/$id': typeof TasksIdRoute
  '/settings/api-keys': typeof SettingsSettingsApiKeysRoute
  '/settings/appearance': typeof SettingsSettingsAppearanceRoute
  '/settings/bots': typeof SettingsSettingsBotsRoute
  '/settings/channels': typeof SettingsSettingsChannelsRoute
  '/settings/periodic-jobs': typeof SettingsSettingsPeriodicJobsRoute
  '/settings/sessions': typeof SettingsSettingsSessionsRoute
  '/settings/uploads': typeof SettingsSettingsUploadsRoute
  '/settings/users': typeof SettingsSettingsUsersRoute
  '/settings': typeof SettingsSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_settings': typeof SettingsRouteWithChildren
  '/files': typeof FilesRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/shared': typeof SharedRoute
  '/shared-with-me': typeof SharedWithMeRoute
  '/storage': typeof StorageRoute
  '/tasks': typeof TasksRoute
  '/trash': typeof TrashRoute
  '/share/$token': typeof ShareTokenRoute
  '/tasks_/$id': typeof TasksIdRoute
  '/_settings/settings/api-keys': typeof SettingsSettingsApiKeysRoute
  '/_settings/settings/appearance': typeof SettingsSettingsAppearanceRoute
  '/_settings/settings/bots': typeof SettingsSettingsBotsRoute
  '/_settings/settings/channels': typeof SettingsSettingsChannelsRoute
  '/_settings/settings/periodic-jobs': typeof SettingsSettingsPeriodicJobsRoute
  '/_settings/settings/sessions': typeof SettingsSettingsSessionsRoute
  '/_settings/settings/uploads': typeof SettingsSettingsUploadsRoute
  '/_settings/settings/users': typeof SettingsSettingsUsersRoute
  '/_settings/settings/': typeof SettingsSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/files'
    | '/login'
    | '/search'
    | '/shared'
    | '/shared-with-me'
    | '/storage'
    | '/tasks'
    | '/trash'
    | '/share/$token'
    | '/tasks/$id'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/bots'
    | '/settings/channels'
    | '/settings/periodic-jobs'
    | '/settings/sessions'
    | '/settings/uploads'
    | '/settings/users'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/files'
    | '/login'
    | '/search'
    | '/shared'
    | '/shared-with-me'
    | '/storage'
    | '/tasks'
    | '/trash'
    | '/share/$token'
    | '/tasks/$id'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/bots'
    | '/settings/channels'
    | '/settings/periodic-jobs'
    | '/settings/sessions'
    | '/settings/uploads'
    | '/settings/users'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_settings'
    | '/files'
    | '/login'
    | '/search'
    | '/shared'
    | '/shared-with-me'
    | '/storage'
    | '/tasks'
    | '/trash'
    | '/share/$token'
    | '/tasks_/$id'
    | '/_settings/settings/api-keys'
    | '/_settings/settings/appearance'
    | '/_settings/settings/bots'
    | '/_settings/settings/channels'
    | '/_settings/settings/periodic-jobs'
    | '/_settings/settings/sessions'
    | '/_settings/settings/uploads'
    | '/_settings/settings/users'
    | '/_settings/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  FilesRoute: typeof FilesRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  SharedRoute: typeof SharedRoute
  SharedWithMeRoute: typeof SharedWithMeRoute
  StorageRoute: typeof StorageRoute
  TasksRoute: typeof TasksRoute
  TrashRoute: typeof TrashRoute
  ShareTokenRoute: typeof ShareTokenRoute
  TasksIdRoute: typeof TasksIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_settings': {
      id: '/_settings'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared': {
      id: '/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared-with-me': {
      id: '/shared-with-me'
      path: '/shared-with-me'
      fullPath: '/shared-with-me'
      preLoaderRoute: typeof SharedWithMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks_/$id': {
      id: '/tasks_/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_settings/settings/': {
      id: '/_settings/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsSettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_settings/settings/api-keys': {
      id: '/_settings/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsSettingsApiKeysRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_settings/settings/appearance': {
      id: '/_settings/settings/appearance'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsSettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_settings/settings/bots': {
      id: '/_settings/settings/bots'
      path: '/settings/bots'
      fullPath: '/settings/bots'
      preLoaderRoute: typeof SettingsSettingsBotsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_settings/settings/channels': {
      id: '/_settings/settings/channels'
      path: '/settings/channels'
      fullPath: '/settings/channels'
      preLoaderRoute: typeof SettingsSettingsChannelsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_settings/settings/periodic-jobs': {
      id: '/_settings/settings/periodic-jobs'
      path: '/settings/periodic-jobs'
      fullPath: '/settings/periodic-jobs'
      preLoaderRoute: typeof SettingsSettingsPeriodicJobsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_settings/settings/sessions': {
      id: '/_settings/settings/sessions'
      path: '/settings/sessions'
      fullPath: '/settings/sessions'
      preLoaderRoute: typeof SettingsSettingsSessionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_settings/settings/uploads': {
      id: '/_settings/settings/uploads'
      path: '/settings/uploads'
      fullPath: '/settings/uploads'
      preLoaderRoute: typeof SettingsSettingsUploadsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_settings/settings/users': {
      id: '/_settings/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsSettingsUsersRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsSettingsApiKeysRoute: typeof SettingsSettingsApiKeysRoute
  SettingsSettingsAppearanceRoute: typeof SettingsSettingsAppearanceRoute
  SettingsSettingsBotsRoute: typeof SettingsSettingsBotsRoute
  SettingsSettingsChannelsRoute: typeof SettingsSettingsChannelsRoute
  SettingsSettingsPeriodicJobsRoute: typeof SettingsSettingsPeriodicJobsRoute
  SettingsSettingsSessionsRoute: typeof SettingsSettingsSessionsRoute
  SettingsSettingsUploadsRoute: typeof SettingsSettingsUploadsRoute
  SettingsSettingsUsersRoute: typeof SettingsSettingsUsersRoute
  SettingsSettingsIndexRoute: typeof SettingsSettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsSettingsApiKeysRoute: SettingsSettingsApiKeysRoute,
  SettingsSettingsAppearanceRoute: SettingsSettingsAppearanceRoute,
  SettingsSettingsBotsRoute: SettingsSettingsBotsRoute,
  SettingsSettingsChannelsRoute: SettingsSettingsChannelsRoute,
  SettingsSettingsPeriodicJobsRoute: SettingsSettingsPeriodicJobsRoute,
  SettingsSettingsSessionsRoute: SettingsSettingsSessionsRoute,
  SettingsSettingsUploadsRoute: SettingsSettingsUploadsRoute,
  SettingsSettingsUsersRoute: SettingsSettingsUsersRoute,
  SettingsSettingsIndexRoute: SettingsSettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRouteWithChildren,
  FilesRoute: FilesRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  SharedRoute: SharedRoute,
  SharedWithMeRoute: SharedWithMeRoute,
  StorageRoute: StorageRoute,
  TasksRoute: TasksRoute,
  TrashRoute: TrashRoute,
  ShareTokenRoute: ShareTokenRoute,
  TasksIdRoute: TasksIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
