package main

// zhDescriptions translates the `description` struct tag of every configuration
// setting for the Simplified Chinese reference page. Keys are the dotted config
// keys the loader accepts, so a rename in internal/config turns a missing entry
// into a visible fallback to the English struct tag rather than a silent
// mistranslation. Section titles and the table headings live in main.go next to
// the rest of the locale definition.
func zhDescriptions() map[string]string {
	return map[string]string{
		"cache.memory.size":                "全局 Ristretto 内存缓存大小（例如 5MB、10MB）",
		"database.application-name":        "PostgreSQL 应用名称",
		"database.auto-migrate-legacy":     "启动时自动迁移检测到的 TelDrive v1 数据库",
		"database.connect-timeout":         "PostgreSQL 连接超时时间",
		"database.health-check-interval":   "PostgreSQL 连接池健康检查间隔",
		"database.max-connection-idle":     "PostgreSQL 连接的最大空闲时间",
		"database.max-connection-life":     "PostgreSQL 连接的最长存活时间",
		"database.max-connections":         "PostgreSQL 最大连接数",
		"database.min-connections":         "PostgreSQL 最小连接数",
		"database.schema":                  "存放所有 TelDrive 表与 River 表的 PostgreSQL schema",
		"database.url":                     "PostgreSQL 连接 URL",
		"encryption.active-key-version":    "新上传使用的当前服务端托管加密密钥版本",
		"encryption.keys":                  "加密密钥，格式为逗号分隔的 version:key 条目",
		"events.batch-size":                "每批 SSE 从 PostgreSQL 读取的最大事件数",
		"events.cleanup-interval":          "过期事件流票据的清理间隔",
		"events.connect-timeout":           "PostgreSQL 事件监听器连接超时时间",
		"events.heartbeat":                 "SSE 心跳间隔",
		"events.max-connections-per-user":  "单个 API 实例上每个用户允许的最大 SSE 并发连接数",
		"events.ping-interval":             "PostgreSQL 事件监听器健康检查间隔",
		"events.reconnect-max":             "PostgreSQL 监听器最大重连延迟",
		"events.reconnect-min":             "PostgreSQL 监听器最小重连延迟",
		"events.ticket-ttl":                "浏览器事件流票据的有效期",
		"events.write-timeout":             "单次 SSE 写入与刷新的最长耗时",
		"http.address":                     "HTTP 监听地址",
		"http.idle-timeout":                "HTTP keep-alive 空闲超时时间",
		"http.read-header-timeout":         "读取请求头的最长等待时间",
		"http.read-timeout":                "读取整个请求的最长时间；设为 0 可对流式上传关闭该限制",
		"http.shutdown-timeout":            "优雅停机的超时时间",
		"http.trusted-proxies":             "允许设置转发头的代理 IP 地址或 CIDR",
		"http.write-timeout":               "响应写入的最长时间；设为 0 可对流式传输关闭该限制",
		"jobs.run-workers":                 "在当前进程中运行 River 后台任务 worker",
		"logging.log-format":               "日志格式：json 或 text",
		"logging.log-level":                "日志级别：debug、info、warn 或 error",
		"security.access-token-ttl":        "访问令牌的有效期",
		"security.allowed-users":           "允许登录的 Telegram 用户名；留空表示允许所有用户",
		"security.data-key":                "用于加密已存储 Telegram 凭据的密钥",
		"security.issuer":                  "JWT 签发者（issuer）",
		"security.login-flow-ttl":          "Telegram 登录流程的有效期",
		"security.refresh-token-ttl":       "刷新令牌的有效期",
		"security.signing-key":             "JWT 签名密钥",
		"telegram.app-hash":                "Telegram 应用 hash",
		"telegram.app-id":                  "Telegram 应用 ID",
		"telegram.app-version":             "Telegram 客户端应用版本",
		"telegram.auto-channel-create":     "自动创建存储频道",
		"telegram.backend":                 "Telegram 后端：remote 或 filesystem",
		"telegram.bot-rotation-backend":    "Bot 轮换后端：memory 适合单实例追求速度，database 用于集群范围协调",
		"telegram.channel-name-prefix":     "自动创建频道时使用的名称前缀",
		"telegram.channel-part-limit":      "单个 Telegram 频道最多存储的分片数",
		"telegram.client-logging":          "通过应用日志输出 gotd 的详细 Telegram 客户端日志",
		"telegram.device-model":            "Telegram 客户端的设备型号",
		"telegram.dial-timeout":            "Telegram 连接超时时间",
		"telegram.download-bots":           "参与下载轮换的已启用 bot 上限；为 0 时使用已认证的用户账号",
		"telegram.download-client-pool":    "在 HTTP 请求之间保持已认证的 Telegram 下载客户端常驻",
		"telegram.download-read-buffers":   "每个下载流在内存中预取的 Telegram 下载分块数量",
		"telegram.download-read-parallel":  "每个下载流并发拉取的 Telegram 分块数",
		"telegram.language-code":           "Telegram 客户端语言代码",
		"telegram.language-pack":           "Telegram 客户端语言包",
		"telegram.local-root":              "本地 Telegram 模拟器使用的文件系统根目录",
		"telegram.max-retries":             "Telegram 传输层最大重试次数",
		"telegram.mtproxy.address":         "MTProto 代理地址，格式为 host:port",
		"telegram.mtproxy.secret":          "MTProto 代理密钥，十六进制格式",
		"telegram.proxy":                   "HTTP、HTTPS 或 SOCKS5 代理地址",
		"telegram.randomize-part-names":    "随机化 Telegram 文档名称",
		"telegram.rate-burst":              "Telegram API 请求的突发额度",
		"telegram.rate-interval":           "两次 Telegram API 请求之间的最小间隔",
		"telegram.rate-limit":              "启用 Telegram API 请求速率限制",
		"telegram.reconnect-timeout":       "Telegram 重连退避的最长等待时间",
		"telegram.system-language-code":    "Telegram 客户端的系统语言代码",
		"telegram.system-version":          "Telegram 客户端的系统版本",
		"telegram.upload-threads":          "并发上传的 Telegram worker 数量",
		"uploads.default-part-size":        "会话未指定分片大小时使用的分片大小，可为字节数或 128MiB 这类带单位的写法",
		"uploads.hashing-enabled":          "为上传的文件计算并保存 BLAKE3 哈希",
		"uploads.local-import-roots":       "允许作为本地后台导入来源的服务端绝对路径目录；留空表示禁用本地导入",
		"uploads.max-concurrent-downloads": "同时保持打开的下载流数量上限",
		"uploads.max-part-size":            "会话可请求的最大分片大小，可为字节数或 4GiB 这类带单位的写法",
		"uploads.session-ttl":              "可续传上传会话的有效期",
	}
}
