// Copies the generated contract next to the documentation site, which serves it
// for the API reference. The tracked copy lives in openapi/ and is regenerated by
// `just generate-openapi`, so this script must run after that step (docs-build
// depends on it).
import { mkdir, copyFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

// source is the contract the TypeSpec build wrote; destination is where the site
// expects to find it when it is bundled.
const source = resolve(import.meta.dir, '../../openapi/teldrive.openapi.yaml');
const destination = resolve(import.meta.dir, '../public/openapi.yaml');

await mkdir(dirname(destination), { recursive: true });
await copyFile(source, destination);
console.log(`synced ${source} -> ${destination}`);
