// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireUserBootstrapLock = `-- name: AcquireUserBootstrapLock :exec
SELECT pg_advisory_xact_lock(846742351)
`

// AcquireUserBootstrapLock takes the fixed transaction-scoped advisory lock that
// serializes user bootstrapping, so two logins cannot both create the first owner.
func (q *Queries) AcquireUserBootstrapLock(ctx context.Context) error {
	_, err := q.db.Exec(ctx, acquireUserBootstrapLock)
	return err
}

const completeTelegramLoginFlow = `-- name: CompleteTelegramLoginFlow :one
UPDATE /* TEMPLATE: schema */telegram_login_flows
SET completed_at = now()
WHERE id = $1
  AND completed_at IS NULL
RETURNING id, method, phone_number_ciphertext, telegram_state_ciphertext, password_required, expires_at, completed_at, created_at
`

// CompleteTelegramLoginFlow marks a still-pending flow as completed and returns it; a
// second completion, or an unknown id, returns no row.
func (q *Queries) CompleteTelegramLoginFlow(ctx context.Context, id pgtype.UUID) (*TelegramLoginFlow, error) {
	row := q.db.QueryRow(ctx, completeTelegramLoginFlow, id)
	var i TelegramLoginFlow
	err := row.Scan(
		&i.ID,
		&i.Method,
		&i.PhoneNumberCiphertext,
		&i.TelegramStateCiphertext,
		&i.PasswordRequired,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO /* TEMPLATE: schema */api_keys (
    id,
    user_id,
    name,
    key_prefix,
    secret_hash,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, user_id, name, key_prefix, secret_hash, last_used_at, expires_at, revoked_at, created_at
`

type CreateAPIKeyParams struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     int64              `json:"user_id"`
	Name       string             `json:"name"`
	KeyPrefix  string             `json:"key_prefix"`
	SecretHash []byte             `json:"secret_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

// CreateAPIKey stores a new API key for the user and returns it; only the secret hash
// and a display prefix are persisted, and a NULL expiry means the key never expires.
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (*ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.KeyPrefix,
		arg.SecretHash,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyPrefix,
		&i.SecretHash,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO /* TEMPLATE: schema */sessions (
    id,
    user_id,
    telegram_session,
    refresh_token_hash,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, user_id, telegram_session, refresh_token_hash, expires_at, last_used_at, revoked_at, created_at
`

type CreateSessionParams struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           int64              `json:"user_id"`
	TelegramSession  []byte             `json:"telegram_session"`
	RefreshTokenHash []byte             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

// CreateSession stores a refresh session for the user and returns it; telegram_session
// is the serialized Telegram session used later to act on the user's behalf.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (*Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TelegramSession,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TelegramSession,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const createTelegramLoginFlow = `-- name: CreateTelegramLoginFlow :one
INSERT INTO /* TEMPLATE: schema */telegram_login_flows (
    id,
    method,
    phone_number_ciphertext,
    telegram_state_ciphertext,
    password_required,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, method, phone_number_ciphertext, telegram_state_ciphertext, password_required, expires_at, completed_at, created_at
`

type CreateTelegramLoginFlowParams struct {
	ID                      pgtype.UUID         `json:"id"`
	Method                  TelegramLoginMethod `json:"method"`
	PhoneNumberCiphertext   []byte              `json:"phone_number_ciphertext"`
	TelegramStateCiphertext []byte              `json:"telegram_state_ciphertext"`
	PasswordRequired        bool                `json:"password_required"`
	ExpiresAt               pgtype.Timestamptz  `json:"expires_at"`
}

// CreateTelegramLoginFlow stores a new pending Telegram login flow and returns it; the
// phone number is optional because a QR-code flow does not know it yet.
func (q *Queries) CreateTelegramLoginFlow(ctx context.Context, arg CreateTelegramLoginFlowParams) (*TelegramLoginFlow, error) {
	row := q.db.QueryRow(ctx, createTelegramLoginFlow,
		arg.ID,
		arg.Method,
		arg.PhoneNumberCiphertext,
		arg.TelegramStateCiphertext,
		arg.PasswordRequired,
		arg.ExpiresAt,
	)
	var i TelegramLoginFlow
	err := row.Scan(
		&i.ID,
		&i.Method,
		&i.PhoneNumberCiphertext,
		&i.TelegramStateCiphertext,
		&i.PasswordRequired,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteExpiredTelegramLoginFlows = `-- name: DeleteExpiredTelegramLoginFlows :execrows
DELETE FROM /* TEMPLATE: schema */telegram_login_flows
WHERE expires_at <= now()
`

// DeleteExpiredTelegramLoginFlows deletes every flow whose expiry has passed and
// returns the number of rows removed.
func (q *Queries) DeleteExpiredTelegramLoginFlows(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredTelegramLoginFlows)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveAPIKeyByHash = `-- name: GetActiveAPIKeyByHash :one
SELECT id, user_id, name, key_prefix, secret_hash, last_used_at, expires_at, revoked_at, created_at
FROM /* TEMPLATE: schema */api_keys
WHERE secret_hash = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
`

// GetActiveAPIKeyByHash resolves a presented secret to its key row, ignoring revoked
// keys and keys whose expiry has passed; a NULL expiry never expires.
func (q *Queries) GetActiveAPIKeyByHash(ctx context.Context, secretHash []byte) (*ApiKey, error) {
	row := q.db.QueryRow(ctx, getActiveAPIKeyByHash, secretHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyPrefix,
		&i.SecretHash,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT id, user_id, telegram_session, refresh_token_hash, expires_at, last_used_at, revoked_at, created_at
FROM /* TEMPLATE: schema */sessions
WHERE id = $1
  AND user_id = $2
  AND revoked_at IS NULL
  AND expires_at > now()
`

type GetActiveSessionParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	UserID    int64       `json:"user_id"`
}

// GetActiveSession returns a session only when it belongs to the user and is neither
// revoked nor expired.
func (q *Queries) GetActiveSession(ctx context.Context, arg GetActiveSessionParams) (*Session, error) {
	row := q.db.QueryRow(ctx, getActiveSession, arg.SessionID, arg.UserID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TelegramSession,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getLatestActiveSessionForUser = `-- name: GetLatestActiveSessionForUser :one
SELECT id, user_id, telegram_session, refresh_token_hash, expires_at, last_used_at, revoked_at, created_at
FROM /* TEMPLATE: schema */sessions
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > now()
ORDER BY last_used_at DESC NULLS LAST, created_at DESC
LIMIT 1
`

// GetLatestActiveSessionForUser returns the user's most recently used live session,
// ordering sessions that were never used by creation time instead.
func (q *Queries) GetLatestActiveSessionForUser(ctx context.Context, userID int64) (*Session, error) {
	row := q.db.QueryRow(ctx, getLatestActiveSessionForUser, userID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TelegramSession,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getSessionByRefreshTokenHash = `-- name: GetSessionByRefreshTokenHash :one
SELECT id, user_id, telegram_session, refresh_token_hash, expires_at, last_used_at, revoked_at, created_at
FROM /* TEMPLATE: schema */sessions
WHERE refresh_token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

// GetSessionByRefreshTokenHash resolves a refresh token hash to its session and
// returns no row once the session is revoked or expired.
func (q *Queries) GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash []byte) (*Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshTokenHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TelegramSession,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getTelegramLoginFlow = `-- name: GetTelegramLoginFlow :one
SELECT id, method, phone_number_ciphertext, telegram_state_ciphertext, password_required, expires_at, completed_at, created_at
FROM /* TEMPLATE: schema */telegram_login_flows
WHERE id = $1
  AND completed_at IS NULL
  AND expires_at > now()
`

// GetTelegramLoginFlow returns a login flow that is still pending and unexpired; a
// completed or expired flow, or a reused id, returns no row.
func (q *Queries) GetTelegramLoginFlow(ctx context.Context, id pgtype.UUID) (*TelegramLoginFlow, error) {
	row := q.db.QueryRow(ctx, getTelegramLoginFlow, id)
	var i TelegramLoginFlow
	err := row.Scan(
		&i.ID,
		&i.Method,
		&i.PhoneNumberCiphertext,
		&i.TelegramStateCiphertext,
		&i.PasswordRequired,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getUser = `-- name: GetUser :one
SELECT user_id, display_name, username, premium, created_at, updated_at, role, disabled_at
FROM /* TEMPLATE: schema */users
WHERE user_id = $1
`

// GetUser returns the full account row of one Telegram user id, including its
// disabled_at, so callers apply their own policy on a disabled account.
func (q *Queries) GetUser(ctx context.Context, userID int64) (*User, error) {
	row := q.db.QueryRow(ctx, getUser, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Username,
		&i.Premium,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.DisabledAt,
	)
	return &i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, user_id, name, key_prefix, secret_hash, last_used_at, expires_at, revoked_at, created_at
FROM /* TEMPLATE: schema */api_keys
WHERE user_id = $1
  AND (
    $2::timestamptz IS NULL
    OR (created_at, id) < (
      $2::timestamptz,
      $3::uuid
    )
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListAPIKeysParams struct {
	UserID         int64              `json:"user_id"`
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterID        pgtype.UUID        `json:"after_id"`
	PageSize       int32              `json:"page_size"`
}

// ListAPIKeys returns one page of the user's API keys, newest first, keyset-paged on
// (created_at, id), including revoked and expired ones.
func (q *Queries) ListAPIKeys(ctx context.Context, arg ListAPIKeysParams) ([]*ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys,
		arg.UserID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeyPrefix,
			&i.SecretHash,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, user_id, telegram_session, refresh_token_hash, expires_at, last_used_at, revoked_at, created_at
FROM /* TEMPLATE: schema */sessions
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > now()
  AND (
    $2::timestamptz IS NULL
    OR (created_at, id) < (
      $2::timestamptz,
      $3::uuid
    )
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListSessionsParams struct {
	UserID         int64              `json:"user_id"`
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterID        pgtype.UUID        `json:"after_id"`
	PageSize       int32              `json:"page_size"`
}

// ListSessions returns one page of the user's live sessions, newest first,
// keyset-paged on (created_at, id); revoked and expired sessions are never listed.
func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]*Session, error) {
	rows, err := q.db.Query(ctx, listSessions,
		arg.UserID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TelegramSession,
			&i.RefreshTokenHash,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, display_name, username, premium, created_at, updated_at, role, disabled_at
FROM /* TEMPLATE: schema */users
WHERE (
    $1::text IS NULL
    OR display_name ILIKE '%' || $1::text || '%'
    OR username ILIKE '%' || $1::text || '%'
    OR user_id::text = $1::text
)
ORDER BY created_at ASC, user_id ASC
LIMIT $2
`

type ListUsersParams struct {
	Search   pgtype.Text `json:"search"`
	PageSize int32       `json:"page_size"`
}

// ListUsers returns up to page_size accounts ordered by creation time, oldest first;
// search matches display name or username case-insensitively, or the exact user id.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]*User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Search, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.DisplayName,
			&i.Username,
			&i.Premium,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE /* TEMPLATE: schema */api_keys
SET revoked_at = now()
WHERE id = $1
  AND user_id = $2
  AND revoked_at IS NULL
`

type RevokeAPIKeyParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID int64       `json:"user_id"`
}

// RevokeAPIKey revokes one key of the user and returns the rows changed, which is zero
// for an unknown, foreign or already revoked key.
func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAllAPIKeysForUser = `-- name: RevokeAllAPIKeysForUser :execrows
UPDATE /* TEMPLATE: schema */api_keys
SET revoked_at = COALESCE(revoked_at, now())
WHERE user_id = $1
  AND revoked_at IS NULL
`

// RevokeAllAPIKeysForUser revokes every live API key of the user and returns the row
// count, leaving already revoked keys untouched.
func (q *Queries) RevokeAllAPIKeysForUser(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllAPIKeysForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAllSessionsForUser = `-- name: RevokeAllSessionsForUser :execrows
UPDATE /* TEMPLATE: schema */sessions
SET revoked_at = COALESCE(revoked_at, now())
WHERE user_id = $1
  AND revoked_at IS NULL
`

// RevokeAllSessionsForUser revokes every live session of the user and returns the row
// count, leaving sessions revoked earlier with their original timestamp.
func (q *Queries) RevokeAllSessionsForUser(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllSessionsForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE /* TEMPLATE: schema */sessions
SET revoked_at = COALESCE(revoked_at, now())
WHERE id = $1
  AND user_id = $2
`

type RevokeSessionParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	UserID    int64       `json:"user_id"`
}

// RevokeSession revokes one session of the given user and returns the row count, which
// is zero when the session belongs to someone else or was already revoked.
func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, arg.SessionID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateSessionRefreshToken = `-- name: RotateSessionRefreshToken :one
UPDATE /* TEMPLATE: schema */sessions
SET refresh_token_hash = $1,
    last_used_at = now()
WHERE id = $2
  AND refresh_token_hash = $3
  AND revoked_at IS NULL
  AND expires_at > now()
RETURNING id, user_id, telegram_session, refresh_token_hash, expires_at, last_used_at, revoked_at, created_at
`

type RotateSessionRefreshTokenParams struct {
	NewRefreshTokenHash []byte      `json:"new_refresh_token_hash"`
	SessionID           pgtype.UUID `json:"session_id"`
	OldRefreshTokenHash []byte      `json:"old_refresh_token_hash"`
}

// RotateSessionRefreshToken swaps in a new refresh token hash and stamps last_used_at,
// but only while the old hash still matches a live session, so a replay fails.
func (q *Queries) RotateSessionRefreshToken(ctx context.Context, arg RotateSessionRefreshTokenParams) (*Session, error) {
	row := q.db.QueryRow(ctx, rotateSessionRefreshToken, arg.NewRefreshTokenHash, arg.SessionID, arg.OldRefreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TelegramSession,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const searchUsersForShare = `-- name: SearchUsersForShare :many
SELECT user_id, display_name, username, premium, created_at, updated_at, role, disabled_at
FROM /* TEMPLATE: schema */users
WHERE user_id <> $1
  AND disabled_at IS NULL
  AND (
    display_name ILIKE '%' || $2::text || '%'
    OR username ILIKE '%' || $2::text || '%'
    OR user_id::text = $2::text
  )
ORDER BY username ASC NULLS LAST, display_name ASC NULLS LAST, user_id ASC
LIMIT $3
`

type SearchUsersForShareParams struct {
	ExcludeUserID int64  `json:"exclude_user_id"`
	Search        string `json:"search"`
	PageSize      int32  `json:"page_size"`
}

// SearchUsersForShare finds share recipients by display name, username or exact
// user id, excluding the caller and disabled accounts, ordered by username.
func (q *Queries) SearchUsersForShare(ctx context.Context, arg SearchUsersForShareParams) ([]*User, error) {
	rows, err := q.db.Query(ctx, searchUsersForShare, arg.ExcludeUserID, arg.Search, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.DisplayName,
			&i.Username,
			&i.Premium,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserDisabled = `-- name: SetUserDisabled :one
UPDATE /* TEMPLATE: schema */users
SET disabled_at = CASE WHEN $1::boolean THEN COALESCE(disabled_at, now()) ELSE NULL END,
    updated_at = now()
WHERE user_id = $2
  AND role <> 'owner'
RETURNING user_id, display_name, username, premium, created_at, updated_at, role, disabled_at
`

type SetUserDisabledParams struct {
	Disabled bool  `json:"disabled"`
	UserID   int64 `json:"user_id"`
}

// SetUserDisabled disables or re-enables a non-owner account, stamping disabled_at on
// the first disable and clearing it on enable; the owner row is never touched.
func (q *Queries) SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) (*User, error) {
	row := q.db.QueryRow(ctx, setUserDisabled, arg.Disabled, arg.UserID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Username,
		&i.Premium,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.DisabledAt,
	)
	return &i, err
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE /* TEMPLATE: schema */api_keys
SET last_used_at = now()
WHERE id = $1
`

// TouchAPIKey records the last use of a key by id, with no owner check and no failure
// when the id no longer exists.
func (q *Queries) TouchAPIKey(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE /* TEMPLATE: schema */sessions
SET last_used_at = now()
WHERE id = $1
  AND revoked_at IS NULL
`

// TouchSession stamps last_used_at on a session that is not revoked; an unknown or
// revoked id is silently ignored.
func (q *Queries) TouchSession(ctx context.Context, sessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, sessionID)
	return err
}

const updateSessionTelegramSession = `-- name: UpdateSessionTelegramSession :execrows
UPDATE /* TEMPLATE: schema */sessions
SET telegram_session = $1,
    last_used_at = now()
WHERE id = $2
  AND user_id = $3
  AND revoked_at IS NULL
  AND expires_at > now()
`

type UpdateSessionTelegramSessionParams struct {
	TelegramSession []byte      `json:"telegram_session"`
	SessionID       pgtype.UUID `json:"session_id"`
	UserID          int64       `json:"user_id"`
}

// UpdateSessionTelegramSession replaces the stored Telegram session of one live
// session and refreshes last_used_at, returning the rows changed.
// The write is scoped to the owner as well, so a session id can never be used to
// rewrite another account's stored Telegram session.
func (q *Queries) UpdateSessionTelegramSession(ctx context.Context, arg UpdateSessionTelegramSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSessionTelegramSession, arg.TelegramSession, arg.SessionID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTelegramLoginFlowState = `-- name: UpdateTelegramLoginFlowState :one
UPDATE /* TEMPLATE: schema */telegram_login_flows
SET telegram_state_ciphertext = $1,
    password_required = $2
WHERE id = $3
  AND completed_at IS NULL
  AND expires_at > now()
RETURNING id, method, phone_number_ciphertext, telegram_state_ciphertext, password_required, expires_at, completed_at, created_at
`

type UpdateTelegramLoginFlowStateParams struct {
	TelegramStateCiphertext []byte      `json:"telegram_state_ciphertext"`
	PasswordRequired        bool        `json:"password_required"`
	ID                      pgtype.UUID `json:"id"`
}

// UpdateTelegramLoginFlowState replaces the stored Telegram state of a flow that is
// still pending and unexpired; a completed or expired flow returns no row.
func (q *Queries) UpdateTelegramLoginFlowState(ctx context.Context, arg UpdateTelegramLoginFlowStateParams) (*TelegramLoginFlow, error) {
	row := q.db.QueryRow(ctx, updateTelegramLoginFlowState, arg.TelegramStateCiphertext, arg.PasswordRequired, arg.ID)
	var i TelegramLoginFlow
	err := row.Scan(
		&i.ID,
		&i.Method,
		&i.PhoneNumberCiphertext,
		&i.TelegramStateCiphertext,
		&i.PasswordRequired,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE /* TEMPLATE: schema */users
SET role = $1, updated_at = now()
WHERE user_id = $2
  AND role <> 'owner'
  AND $1::/* TEMPLATE: schema */user_role IN ('admin', 'user')
RETURNING user_id, display_name, username, premium, created_at, updated_at, role, disabled_at
`

type UpdateUserRoleParams struct {
	Role   UserRole `json:"role"`
	UserID int64    `json:"user_id"`
}

// UpdateUserRole sets a non-owner account to 'admin' or 'user' and returns the updated
// row; targeting the owner, or any other role value, returns no row.
func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (*User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.Role, arg.UserID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Username,
		&i.Premium,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.DisabledAt,
	)
	return &i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO /* TEMPLATE: schema */users (
    user_id,
    display_name,
    username,
    premium,
    role
) VALUES (
    $1,
    $2,
    $3,
    $4,
    CASE
        WHEN EXISTS (SELECT 1 FROM /* TEMPLATE: schema */users) THEN 'user'::/* TEMPLATE: schema */user_role
        ELSE 'owner'::/* TEMPLATE: schema */user_role
    END
)
ON CONFLICT (user_id) DO UPDATE
SET display_name = EXCLUDED.display_name,
    username = EXCLUDED.username,
    premium = EXCLUDED.premium,
    updated_at = now()
RETURNING user_id, display_name, username, premium, created_at, updated_at, role, disabled_at
`

type UpsertUserParams struct {
	UserID      int64       `json:"user_id"`
	DisplayName pgtype.Text `json:"display_name"`
	Username    pgtype.Text `json:"username"`
	Premium     bool        `json:"premium"`
}

// UpsertUser inserts the Telegram profile of one user or refreshes it on the next
// login and returns the row; the first user ever inserted is granted the owner role.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.UserID,
		arg.DisplayName,
		arg.Username,
		arg.Premium,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Username,
		&i.Premium,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.DisabledAt,
	)
	return &i, err
}
