// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateBot = `-- name: ActivateBot :one
UPDATE /* TEMPLATE: schema */bots
SET username = $1,
    enabled = TRUE,
    consecutive_failures = 0,
    last_error = NULL,
    retry_after = NULL,
    updated_at = now()
WHERE user_id = $2
  AND bot_id = $3
RETURNING bot_id, user_id, username, token_ciphertext, enabled, session, consecutive_failures, last_error, last_used_at, retry_after, created_at, updated_at
`

type ActivateBotParams struct {
	Username pgtype.Text `json:"username"`
	UserID   int64       `json:"user_id"`
	BotID    int64       `json:"bot_id"`
}

// ActivateBot records the username Telegram reported and clears the failure
// history, putting the bot back into service; an unknown bot returns no row.
func (q *Queries) ActivateBot(ctx context.Context, arg ActivateBotParams) (*Bot, error) {
	row := q.db.QueryRow(ctx, activateBot, arg.Username, arg.UserID, arg.BotID)
	var i Bot
	err := row.Scan(
		&i.BotID,
		&i.UserID,
		&i.Username,
		&i.TokenCiphertext,
		&i.Enabled,
		&i.Session,
		&i.ConsecutiveFailures,
		&i.LastError,
		&i.LastUsedAt,
		&i.RetryAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const clearSelectedChannel = `-- name: ClearSelectedChannel :exec
UPDATE /* TEMPLATE: schema */channels
SET selected = FALSE,
    updated_at = now()
WHERE user_id = $1
  AND selected
`

// ClearSelectedChannel deselects whichever channel the user currently has selected,
// which the one-selected-per-user index requires before another can be promoted.
func (q *Queries) ClearSelectedChannel(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, clearSelectedChannel, userID)
	return err
}

const countChannelReferences = `-- name: CountChannelReferences :one
SELECT (
    (SELECT count(*) FROM /* TEMPLATE: schema */file_parts fp WHERE fp.channel_id = $1) +
    (SELECT count(*) FROM /* TEMPLATE: schema */upload_parts up WHERE up.channel_id = $1)
)::bigint AS reference_count
`

// CountChannelReferences counts the file parts and upload parts that still point
// at the channel for any user, to decide whether it may be forgotten.
func (q *Queries) CountChannelReferences(ctx context.Context, targetChannelID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countChannelReferences, targetChannelID)
	var reference_count int64
	err := row.Scan(&reference_count)
	return reference_count, err
}

const countChannelStoredMessages = `-- name: CountChannelStoredMessages :one
SELECT count(*)::bigint
FROM (
    SELECT fp.channel_id, fp.message_id
    FROM /* TEMPLATE: schema */file_parts fp
    WHERE fp.channel_id = $1
    UNION
    SELECT up.channel_id, up.message_id
    FROM /* TEMPLATE: schema */upload_parts up
    WHERE up.channel_id = $1
      AND message_id IS NOT NULL
) AS stored_messages
`

// CountChannelStoredMessages counts the distinct Telegram messages referenced by
// the channel's file and upload parts, ignoring upload parts without a message.
func (q *Queries) CountChannelStoredMessages(ctx context.Context, targetChannelID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countChannelStoredMessages, targetChannelID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createChannel = `-- name: CreateChannel :one
INSERT INTO /* TEMPLATE: schema */channels (
    channel_id,
    user_id,
    name,
    selected
) VALUES (
    $1,
    $2,
    $3,
    FALSE
)
RETURNING channel_id, user_id, name, selected, health, last_checked_at, created_at, updated_at
`

type CreateChannelParams struct {
	ChannelID int64  `json:"channel_id"`
	UserID    int64  `json:"user_id"`
	Name      string `json:"name"`
}

// CreateChannel inserts a channel for the user, always unselected, and returns it;
// health stays at its default until the first check.
func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (*Channel, error) {
	row := q.db.QueryRow(ctx, createChannel, arg.ChannelID, arg.UserID, arg.Name)
	var i Channel
	err := row.Scan(
		&i.ChannelID,
		&i.UserID,
		&i.Name,
		&i.Selected,
		&i.Health,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteBot = `-- name: DeleteBot :execrows
DELETE FROM /* TEMPLATE: schema */bots
WHERE user_id = $1
  AND bot_id = $2
`

type DeleteBotParams struct {
	UserID int64 `json:"user_id"`
	BotID  int64 `json:"bot_id"`
}

// DeleteBot removes one bot of the user and returns the rows deleted.
func (q *Queries) DeleteBot(ctx context.Context, arg DeleteBotParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBot, arg.UserID, arg.BotID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteChannel = `-- name: DeleteChannel :execrows
DELETE FROM /* TEMPLATE: schema */channels
WHERE user_id = $1
  AND channel_id = $2
  AND NOT selected
`

type DeleteChannelParams struct {
	UserID    int64 `json:"user_id"`
	ChannelID int64 `json:"channel_id"`
}

// DeleteChannel removes one channel of the user and returns the rows deleted,
// refusing the selected channel so the upload destination cannot disappear.
func (q *Queries) DeleteChannel(ctx context.Context, arg DeleteChannelParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannel, arg.UserID, arg.ChannelID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBot = `-- name: GetBot :one
SELECT bot_id, user_id, username, token_ciphertext, enabled, session, consecutive_failures, last_error, last_used_at, retry_after, created_at, updated_at
FROM /* TEMPLATE: schema */bots
WHERE user_id = $1
  AND bot_id = $2
`

type GetBotParams struct {
	UserID int64 `json:"user_id"`
	BotID  int64 `json:"bot_id"`
}

// GetBot returns one bot of the user by id, or no row when the user has no such bot.
func (q *Queries) GetBot(ctx context.Context, arg GetBotParams) (*Bot, error) {
	row := q.db.QueryRow(ctx, getBot, arg.UserID, arg.BotID)
	var i Bot
	err := row.Scan(
		&i.BotID,
		&i.UserID,
		&i.Username,
		&i.TokenCiphertext,
		&i.Enabled,
		&i.Session,
		&i.ConsecutiveFailures,
		&i.LastError,
		&i.LastUsedAt,
		&i.RetryAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getChannelForUser = `-- name: GetChannelForUser :one
SELECT channel_id, user_id, name, selected, health, last_checked_at, created_at, updated_at
FROM /* TEMPLATE: schema */channels
WHERE user_id = $1
  AND channel_id = $2
`

type GetChannelForUserParams struct {
	UserID    int64 `json:"user_id"`
	ChannelID int64 `json:"channel_id"`
}

// GetChannelForUser returns the user's own channel row, so an id belonging to
// another account returns no row.
func (q *Queries) GetChannelForUser(ctx context.Context, arg GetChannelForUserParams) (*Channel, error) {
	row := q.db.QueryRow(ctx, getChannelForUser, arg.UserID, arg.ChannelID)
	var i Channel
	err := row.Scan(
		&i.ChannelID,
		&i.UserID,
		&i.Name,
		&i.Selected,
		&i.Health,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getSelectedChannel = `-- name: GetSelectedChannel :one
SELECT channel_id, user_id, name, selected, health, last_checked_at, created_at, updated_at
FROM /* TEMPLATE: schema */channels
WHERE user_id = $1
  AND selected
`

// GetSelectedChannel returns the single channel the user selected as the upload
// destination; a user without one gets no row.
func (q *Queries) GetSelectedChannel(ctx context.Context, userID int64) (*Channel, error) {
	row := q.db.QueryRow(ctx, getSelectedChannel, userID)
	var i Channel
	err := row.Scan(
		&i.ChannelID,
		&i.UserID,
		&i.Name,
		&i.Selected,
		&i.Health,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const insertPendingBots = `-- name: InsertPendingBots :many
INSERT INTO /* TEMPLATE: schema */bots AS bot (
    bot_id, user_id, token_ciphertext, enabled
)
SELECT input.bot_id, $1, decode(input.token_ciphertext, 'base64'), false
FROM jsonb_to_recordset($2::jsonb) AS input(
    bot_id bigint, token_ciphertext text
)
ON CONFLICT (user_id, bot_id) DO UPDATE
SET token_ciphertext = EXCLUDED.token_ciphertext,
    enabled = false,
    username = NULL,
    consecutive_failures = 0,
    last_error = NULL,
    retry_after = NULL,
    updated_at = now()
RETURNING bot.bot_id, bot.user_id, bot.username, bot.token_ciphertext, bot.enabled, bot.session, bot.consecutive_failures, bot.last_error, bot.last_used_at, bot.retry_after, bot.created_at, bot.updated_at
`

type InsertPendingBotsParams struct {
	UserID int64  `json:"user_id"`
	Bots   []byte `json:"bots"`
}

// InsertPendingBots registers the given bot ids for the user in the pending,
// disabled state and returns the stored rows; an existing bot is reused and reset.
// Registering a token again replaces the stored one and puts the bot back in the
// pending state, which is the only way a bot that was disabled by a failed
// provisioning can be tried again: the row is identified by its bot id, so an
// existing row has to be reused rather than inserted next to. The failure history
// is cleared with it, because the new attempt starts from nothing.
func (q *Queries) InsertPendingBots(ctx context.Context, arg InsertPendingBotsParams) ([]*Bot, error) {
	rows, err := q.db.Query(ctx, insertPendingBots, arg.UserID, arg.Bots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Bot{}
	for rows.Next() {
		var i Bot
		if err := rows.Scan(
			&i.BotID,
			&i.UserID,
			&i.Username,
			&i.TokenCiphertext,
			&i.Enabled,
			&i.Session,
			&i.ConsecutiveFailures,
			&i.LastError,
			&i.LastUsedAt,
			&i.RetryAfter,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBots = `-- name: ListBots :many
SELECT bot_id, user_id, username, token_ciphertext, enabled, session, consecutive_failures, last_error, last_used_at, retry_after, created_at, updated_at
FROM /* TEMPLATE: schema */bots
WHERE user_id = $1
  AND (
    $2::timestamptz IS NULL
    OR (created_at, bot_id) < (
      $2::timestamptz,
      $3::bigint
    )
  )
ORDER BY created_at DESC, bot_id DESC
LIMIT $4
`

type ListBotsParams struct {
	UserID         int64              `json:"user_id"`
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterBotID     pgtype.Int8        `json:"after_bot_id"`
	PageSize       int32              `json:"page_size"`
}

// ListBots returns one page of the user's bots, newest first, keyset-paged on
// (created_at, bot_id).
func (q *Queries) ListBots(ctx context.Context, arg ListBotsParams) ([]*Bot, error) {
	rows, err := q.db.Query(ctx, listBots,
		arg.UserID,
		arg.AfterCreatedAt,
		arg.AfterBotID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Bot{}
	for rows.Next() {
		var i Bot
		if err := rows.Scan(
			&i.BotID,
			&i.UserID,
			&i.Username,
			&i.TokenCiphertext,
			&i.Enabled,
			&i.Session,
			&i.ConsecutiveFailures,
			&i.LastError,
			&i.LastUsedAt,
			&i.RetryAfter,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelReferencedParts = `-- name: ListChannelReferencedParts :many
SELECT fp.message_id::bigint AS message_id, f.id AS file_id, f.name AS file_name, f.size AS file_size
FROM /* TEMPLATE: schema */file_parts fp
JOIN /* TEMPLATE: schema */files f ON f.id = fp.file_id
WHERE fp.channel_id = $1
  AND f.user_id = $2
  AND f.status = 'active'
ORDER BY f.name, fp.message_id
`

type ListChannelReferencedPartsParams struct {
	TargetChannelID int64 `json:"target_channel_id"`
	TargetUserID    int64 `json:"target_user_id"`
}

type ListChannelReferencedPartsRow struct {
	MessageID int64       `json:"message_id"`
	FileID    pgtype.UUID `json:"file_id"`
	FileName  string      `json:"file_name"`
	FileSize  pgtype.Int8 `json:"file_size"`
}

// ListChannelReferencedParts lists the channel's parts that belong to active files
// of one user with their file name and size, ordered by file name.
func (q *Queries) ListChannelReferencedParts(ctx context.Context, arg ListChannelReferencedPartsParams) ([]*ListChannelReferencedPartsRow, error) {
	rows, err := q.db.Query(ctx, listChannelReferencedParts, arg.TargetChannelID, arg.TargetUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListChannelReferencedPartsRow{}
	for rows.Next() {
		var i ListChannelReferencedPartsRow
		if err := rows.Scan(
			&i.MessageID,
			&i.FileID,
			&i.FileName,
			&i.FileSize,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannels = `-- name: ListChannels :many
SELECT channel_id, user_id, name, selected, health, last_checked_at, created_at, updated_at
FROM /* TEMPLATE: schema */channels
WHERE user_id = $1
  AND (
    $2::timestamptz IS NULL
    OR (created_at, channel_id) < (
      $2::timestamptz,
      $3::bigint
    )
  )
ORDER BY created_at DESC, channel_id DESC
LIMIT $4
`

type ListChannelsParams struct {
	UserID         int64              `json:"user_id"`
	AfterCreatedAt pgtype.Timestamptz `json:"after_created_at"`
	AfterChannelID pgtype.Int8        `json:"after_channel_id"`
	PageSize       int32              `json:"page_size"`
}

// ListChannels returns one page of the user's channels, newest first, keyset-paged
// on (created_at, channel_id) so paging stays stable while rows are inserted.
func (q *Queries) ListChannels(ctx context.Context, arg ListChannelsParams) ([]*Channel, error) {
	rows, err := q.db.Query(ctx, listChannels,
		arg.UserID,
		arg.AfterCreatedAt,
		arg.AfterChannelID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ChannelID,
			&i.UserID,
			&i.Name,
			&i.Selected,
			&i.Health,
			&i.LastCheckedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsForOrphanCleanup = `-- name: ListChannelsForOrphanCleanup :many
SELECT channel_id, user_id, name, selected, health, last_checked_at, created_at, updated_at
FROM /* TEMPLATE: schema */channels
ORDER BY user_id, channel_id
`

// ListChannelsForOrphanCleanup returns every channel of every user ordered by user
// and channel id, because the orphan sweep walks the Telegram side per channel.
func (q *Queries) ListChannelsForOrphanCleanup(ctx context.Context) ([]*Channel, error) {
	rows, err := q.db.Query(ctx, listChannelsForOrphanCleanup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ChannelID,
			&i.UserID,
			&i.Name,
			&i.Selected,
			&i.Health,
			&i.LastCheckedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledBots = `-- name: ListEnabledBots :many
SELECT bot_id, user_id, username, token_ciphertext, enabled, session, consecutive_failures, last_error, last_used_at, retry_after, created_at, updated_at
FROM /* TEMPLATE: schema */bots
WHERE user_id = $1
  AND enabled
ORDER BY bot_id
`

// ListEnabledBots returns every enabled bot of the user ordered by id, ignoring
// retry_after; callers that must honour the backoff need ListUploadEligibleBots.
func (q *Queries) ListEnabledBots(ctx context.Context, userID int64) ([]*Bot, error) {
	rows, err := q.db.Query(ctx, listEnabledBots, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Bot{}
	for rows.Next() {
		var i Bot
		if err := rows.Scan(
			&i.BotID,
			&i.UserID,
			&i.Username,
			&i.TokenCiphertext,
			&i.Enabled,
			&i.Session,
			&i.ConsecutiveFailures,
			&i.LastError,
			&i.LastUsedAt,
			&i.RetryAfter,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferencedMessageIDs = `-- name: ListReferencedMessageIDs :many
SELECT message_id
FROM (
    SELECT fp.message_id
    FROM /* TEMPLATE: schema */file_parts fp
    WHERE fp.channel_id = $1
      AND fp.message_id = ANY($2::bigint[])
    UNION
    SELECT up.message_id
    FROM /* TEMPLATE: schema */upload_parts up
    WHERE up.channel_id = $1
      AND up.message_id = ANY($2::bigint[])
) AS referenced_messages
`

type ListReferencedMessageIDsParams struct {
	TargetChannelID int64   `json:"target_channel_id"`
	MessageIds      []int64 `json:"message_ids"`
}

// ListReferencedMessageIDs returns which of the given message ids a file or upload
// part still references in the channel, so the rest can be deleted from Telegram.
func (q *Queries) ListReferencedMessageIDs(ctx context.Context, arg ListReferencedMessageIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listReferencedMessageIDs, arg.TargetChannelID, arg.MessageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var message_id int64
		if err := rows.Scan(&message_id); err != nil {
			return nil, err
		}
		items = append(items, message_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploadEligibleBots = `-- name: ListUploadEligibleBots :many
SELECT bot_id, user_id, username, token_ciphertext, enabled, session, consecutive_failures, last_error, last_used_at, retry_after, created_at, updated_at
FROM /* TEMPLATE: schema */bots
WHERE user_id = $1
  AND enabled
  AND (retry_after IS NULL OR retry_after <= now())
ORDER BY bot_id
`

// ListUploadEligibleBots returns the enabled bots of the user whose retry_after
// has passed, ordered by id, which is the pool uploads allocate from.
func (q *Queries) ListUploadEligibleBots(ctx context.Context, userID int64) ([]*Bot, error) {
	rows, err := q.db.Query(ctx, listUploadEligibleBots, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Bot{}
	for rows.Next() {
		var i Bot
		if err := rows.Scan(
			&i.BotID,
			&i.UserID,
			&i.Username,
			&i.TokenCiphertext,
			&i.Enabled,
			&i.Session,
			&i.ConsecutiveFailures,
			&i.LastError,
			&i.LastUsedAt,
			&i.RetryAfter,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBotProvisionFailure = `-- name: MarkBotProvisionFailure :execrows
UPDATE /* TEMPLATE: schema */bots
SET enabled = FALSE,
    consecutive_failures = consecutive_failures + 1,
    last_error = $1,
    updated_at = now()
WHERE user_id = $2
  AND bot_id = $3
`

type MarkBotProvisionFailureParams struct {
	LastError pgtype.Text `json:"last_error"`
	UserID    int64       `json:"user_id"`
	BotID     int64       `json:"bot_id"`
}

// MarkBotProvisionFailure disables the bot, increments its failure counter and
// stores the error, returning the rows changed.
func (q *Queries) MarkBotProvisionFailure(ctx context.Context, arg MarkBotProvisionFailureParams) (int64, error) {
	result, err := q.db.Exec(ctx, markBotProvisionFailure, arg.LastError, arg.UserID, arg.BotID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markBotUploadFailure = `-- name: MarkBotUploadFailure :execrows
UPDATE /* TEMPLATE: schema */bots
SET consecutive_failures = consecutive_failures + 1,
    last_error = left($1, 1000),
    -- The wait doubles with every consecutive failure, from thirty seconds up to
    -- six hours, so a bot that keeps failing is retried rarely instead of every
    -- thirtieth second while a transient failure is retried promptly. A success
    -- resets the counter, which puts the bot back at the front of the queue.
    retry_after = now() + make_interval(secs => LEAST(30 * power(2, LEAST(consecutive_failures, 16)), 21600)),
    updated_at = now()
WHERE user_id = $2
  AND bot_id = $3
`

type MarkBotUploadFailureParams struct {
	LastError string `json:"last_error"`
	UserID    int64  `json:"user_id"`
	BotID     int64  `json:"bot_id"`
}

// MarkBotUploadFailure increments the bot's failure counter, keeps its last error
// and defers the next attempt with an exponential backoff.
func (q *Queries) MarkBotUploadFailure(ctx context.Context, arg MarkBotUploadFailureParams) (int64, error) {
	result, err := q.db.Exec(ctx, markBotUploadFailure, arg.LastError, arg.UserID, arg.BotID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markBotUploadSuccess = `-- name: MarkBotUploadSuccess :execrows
UPDATE /* TEMPLATE: schema */bots
SET consecutive_failures = 0,
    last_error = NULL,
    last_used_at = now(),
    retry_after = NULL,
    updated_at = now()
WHERE user_id = $1
  AND bot_id = $2
`

type MarkBotUploadSuccessParams struct {
	UserID int64 `json:"user_id"`
	BotID  int64 `json:"bot_id"`
}

// MarkBotUploadSuccess clears the failure state of the bot and stamps last_used_at,
// which puts it back at the front of the allocation order.
func (q *Queries) MarkBotUploadSuccess(ctx context.Context, arg MarkBotUploadSuccessParams) (int64, error) {
	result, err := q.db.Exec(ctx, markBotUploadSuccess, arg.UserID, arg.BotID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const nextBotSelectionValue = `-- name: NextBotSelectionValue :one
INSERT INTO /* TEMPLATE: schema */bot_selection_counters (
    user_id,
    operation,
    next_value
) VALUES (
    $1,
    $2,
    1
)
ON CONFLICT (user_id, operation) DO UPDATE
SET next_value = /* TEMPLATE: schema */bot_selection_counters.next_value + 1,
    updated_at = now()
RETURNING (next_value - 1)::bigint AS selection_value
`

type NextBotSelectionValueParams struct {
	UserID    int64  `json:"user_id"`
	Operation string `json:"operation"`
}

// NextBotSelectionValue advances the per-user, per-operation round-robin counter
// and returns the value to use, so concurrent allocators get distinct values.
func (q *Queries) NextBotSelectionValue(ctx context.Context, arg NextBotSelectionValueParams) (int64, error) {
	row := q.db.QueryRow(ctx, nextBotSelectionValue, arg.UserID, arg.Operation)
	var selection_value int64
	err := row.Scan(&selection_value)
	return selection_value, err
}

const selectChannel = `-- name: SelectChannel :one
UPDATE /* TEMPLATE: schema */channels
SET selected = TRUE,
    updated_at = now()
WHERE user_id = $1
  AND channel_id = $2
RETURNING channel_id, user_id, name, selected, health, last_checked_at, created_at, updated_at
`

type SelectChannelParams struct {
	UserID    int64 `json:"user_id"`
	ChannelID int64 `json:"channel_id"`
}

// SelectChannel marks one of the user's channels as selected and returns it; the
// caller clears the previous selection first, and an unknown id returns no row.
func (q *Queries) SelectChannel(ctx context.Context, arg SelectChannelParams) (*Channel, error) {
	row := q.db.QueryRow(ctx, selectChannel, arg.UserID, arg.ChannelID)
	var i Channel
	err := row.Scan(
		&i.ChannelID,
		&i.UserID,
		&i.Name,
		&i.Selected,
		&i.Health,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateBotSession = `-- name: UpdateBotSession :execrows
UPDATE /* TEMPLATE: schema */bots
SET session = $1,
    updated_at = now()
WHERE user_id = $2
  AND bot_id = $3
`

type UpdateBotSessionParams struct {
	Session []byte `json:"session"`
	UserID  int64  `json:"user_id"`
	BotID   int64  `json:"bot_id"`
}

// UpdateBotSession stores the serialized Telegram session of one bot and returns
// the rows changed, so a stale bot id is reported as zero.
func (q *Queries) UpdateBotSession(ctx context.Context, arg UpdateBotSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBotSession, arg.Session, arg.UserID, arg.BotID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateChannelHealth = `-- name: UpdateChannelHealth :one
UPDATE /* TEMPLATE: schema */channels
SET health = $1,
    last_checked_at = now(),
    updated_at = now()
WHERE user_id = $2
  AND channel_id = $3
RETURNING channel_id, user_id, name, selected, health, last_checked_at, created_at, updated_at
`

type UpdateChannelHealthParams struct {
	Health    ChannelHealth `json:"health"`
	UserID    int64         `json:"user_id"`
	ChannelID int64         `json:"channel_id"`
}

// UpdateChannelHealth stores the latest health verdict and stamps last_checked_at
// and updated_at; an unknown channel id returns no row.
func (q *Queries) UpdateChannelHealth(ctx context.Context, arg UpdateChannelHealthParams) (*Channel, error) {
	row := q.db.QueryRow(ctx, updateChannelHealth, arg.Health, arg.UserID, arg.ChannelID)
	var i Channel
	err := row.Scan(
		&i.ChannelID,
		&i.UserID,
		&i.Name,
		&i.Selected,
		&i.Health,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const upsertDiscoveredChannels = `-- name: UpsertDiscoveredChannels :many
INSERT INTO /* TEMPLATE: schema */channels AS channel (
    channel_id, user_id, name, selected, health
)
SELECT input.channel_id, $1, input.name, false, 'unknown'
FROM jsonb_to_recordset($2::jsonb) AS input(
    channel_id bigint, name text
)
ON CONFLICT (user_id, channel_id) DO UPDATE
SET name = EXCLUDED.name,
    updated_at = now()
RETURNING channel.channel_id, channel.user_id, channel.name, channel.selected, channel.health, channel.last_checked_at, channel.created_at, channel.updated_at
`

type UpsertDiscoveredChannelsParams struct {
	UserID   int64  `json:"user_id"`
	Channels []byte `json:"channels"`
}

// UpsertDiscoveredChannels records the channels found by discovery, inserting them
// unselected with unknown health and refreshing the name of the existing ones.
func (q *Queries) UpsertDiscoveredChannels(ctx context.Context, arg UpsertDiscoveredChannelsParams) ([]*Channel, error) {
	rows, err := q.db.Query(ctx, upsertDiscoveredChannels, arg.UserID, arg.Channels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ChannelID,
			&i.UserID,
			&i.Name,
			&i.Selected,
			&i.Health,
			&i.LastCheckedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
