// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listDeletionPendingRoots = `-- name: ListDeletionPendingRoots :many
SELECT f.user_id, f.id AS file_id
FROM /* TEMPLATE: schema */files f
WHERE f.status = 'deletion_pending'
  AND (
    f.parent_id IS NULL
    OR NOT EXISTS (
      SELECT 1
      FROM /* TEMPLATE: schema */files parent
      WHERE parent.id = f.parent_id
        AND parent.user_id = f.user_id
        AND parent.status = 'deletion_pending'
    )
  )
ORDER BY f.updated_at, f.id
LIMIT 1000
`

type ListDeletionPendingRootsRow struct {
	UserID int64       `json:"user_id"`
	FileID pgtype.UUID `json:"file_id"`
}

// ListDeletionPendingRoots returns up to 1000 deletion-pending files that are roots
// of their pending subtree, meaning no deletion-pending parent above them, oldest
// update first, so the purge worker deletes whole subtrees from the top.
func (q *Queries) ListDeletionPendingRoots(ctx context.Context) ([]*ListDeletionPendingRootsRow, error) {
	rows, err := q.db.Query(ctx, listDeletionPendingRoots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListDeletionPendingRootsRow{}
	for rows.Next() {
		var i ListDeletionPendingRootsRow
		if err := rows.Scan(&i.UserID, &i.FileID); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashedRootsBefore = `-- name: ListTrashedRootsBefore :many
SELECT f.user_id, f.id AS file_id
FROM /* TEMPLATE: schema */files f
WHERE f.status = 'trashed'
  AND f.deleted_at IS NOT NULL
  AND f.deleted_at <= $1
  AND (
    f.parent_id IS NULL
    OR NOT EXISTS (
      SELECT 1
      FROM /* TEMPLATE: schema */files parent
      WHERE parent.id = f.parent_id
        AND parent.user_id = f.user_id
        AND parent.status = 'trashed'
    )
  )
ORDER BY f.deleted_at, f.id
LIMIT 1000
`

type ListTrashedRootsBeforeRow struct {
	UserID int64       `json:"user_id"`
	FileID pgtype.UUID `json:"file_id"`
}

// ListTrashedRootsBefore returns up to 1000 trashed roots deleted at or before the
// cutoff, skipping rows whose parent is itself trashed, oldest deletion first, so the
// expiry worker purges a whole subtree once instead of walking into it.
func (q *Queries) ListTrashedRootsBefore(ctx context.Context, deletedBefore pgtype.Timestamptz) ([]*ListTrashedRootsBeforeRow, error) {
	rows, err := q.db.Query(ctx, listTrashedRootsBefore, deletedBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListTrashedRootsBeforeRow{}
	for rows.Next() {
		var i ListTrashedRootsBeforeRow
		if err := rows.Scan(&i.UserID, &i.FileID); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
