// Package sqlcgen holds the PostgreSQL query layer generated by sqlc from
// db/queries, together with the handwritten schema plumbing in this file that
// renders the schema template markers of every generated statement into the
// schema configured at start-up.
//
// All other files in this directory are produced by `just generate-db` and must
// not be edited by hand; schema_template.go and its test are the only files
// maintained here.
package sqlcgen

import (
	"context"
	"fmt"
	"regexp"
	"strings"
	"sync/atomic"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// schemaTemplateMarker is the placeholder sqlc leaves in front of every
// qualified object name in the generated statements. It is replaced at run time
// with the configured schema so one build can address any schema.
const schemaTemplateMarker = "/* TEMPLATE: schema */"

// schemaNamePattern is the only shape ConfigureSchema accepts: a plain SQL
// identifier that needs no quoting and cannot smuggle in a second statement.
// configuredSchema holds the schema every generated statement is rendered
// against; it is an atomic.Value because ConfigureSchema runs during start-up
// while query calls may already be in flight.
var (
	schemaNamePattern = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)
	configuredSchema  atomic.Value
)

func init() {
	// The default keeps generated queries working for callers that never call
	// ConfigureSchema, which is also the schema the migrations create.
	configuredSchema.Store("teldrive")
}

// ConfigureSchema sets the explicit PostgreSQL schema rendered into generated queries.
func ConfigureSchema(schema string) error {
	schema = strings.TrimSpace(schema)
	if !schemaNamePattern.MatchString(schema) {
		return fmt.Errorf("invalid database schema %q", schema)
	}
	configuredSchema.Store(schema)
	return nil
}

// QualifiedName returns a safely quoted object name in the configured schema.
func QualifiedName(name string) string {
	return pgx.Identifier{configuredSchema.Load().(string), name}.Sanitize()
}

// wrapDBTX returns db wrapped so every statement it executes has its schema
// markers rendered first. A connection that is already wrapped is returned
// unchanged, which keeps a second wrap from nesting the rewriting.
func wrapDBTX(db DBTX) DBTX {
	if _, ok := db.(*schemaDBTX); ok {
		return db
	}
	return &schemaDBTX{DBTX: db}
}

// schemaDBTX is the DBTX that resolves the schema template markers on the way
// to the underlying connection.
type schemaDBTX struct {
	// DBTX supplies Begin, Commit and Rollback unchanged; only the statement
	// calls below rewrite the query before it reaches the connection.
	DBTX
}

// renderSchema replaces every schema template marker with the configured schema
// quoted for PostgreSQL, so the statement addresses that schema's tables.
func renderSchema(query string) string {
	schema := configuredSchema.Load().(string)
	return strings.ReplaceAll(query, schemaTemplateMarker, pgx.Identifier{schema}.Sanitize()+".")
}

// Exec runs query with the schema markers rendered and discards the rows.
func (db *schemaDBTX) Exec(ctx context.Context, query string, args ...interface{}) (pgconn.CommandTag, error) {
	return db.DBTX.Exec(ctx, renderSchema(query), args...)
}

// Query runs query with the schema markers rendered and returns the rows.
func (db *schemaDBTX) Query(ctx context.Context, query string, args ...interface{}) (pgx.Rows, error) {
	return db.DBTX.Query(ctx, renderSchema(query), args...)
}

// QueryRow runs query with the schema markers rendered and returns a single row.
func (db *schemaDBTX) QueryRow(ctx context.Context, query string, args ...interface{}) pgx.Row {
	return db.DBTX.QueryRow(ctx, renderSchema(query), args...)
}
